[build-system]
requires = ["setuptools>=61.0.0", "wheel"]

[project]
name = "devinterp"
version = "2.0.1"
description = "A library for doing research on developmental interpretability"
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=2.14.0",
    "numpy>=1.23.5",
    "pandas>=1.5.3",
    "pydantic>=2.0.0",
    "torch>=2.0.1",
    "tqdm>=4.65.0",
    "transformers",
    "xarray>=2024.1.0",
    "zarr>=3.1.0,<3.2",
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
    "pytest==7.4.3",
    "pytest-cov>=6.0.0",
    "pytest-xdist>=3.6.1",
    "syrupy"
]

docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-math-dollar",
    "sphinx-autobuild",
    "myst_parser",
]

[project.urls]
"Homepage" = "https://github.com/timaeus-research/devinterp"
"Bug Tracker" = "https://github.com/timaeus-research/devinterp/issues"

[tool.setuptools]
package-dir = {"" = "src"}
