"""Generated model structure data for weight restrictions."""

HEAD_STRUCTURES: dict[str, dict | list[dict]] = {
    "hooked_transformer": [
        {  # MHA (W_K/W_V have n_heads as dim 0)
            "layer_prefixes": ["blocks"],
            "embed": ["embed.W_E"],
            "unembed": ["unembed.W_U", "unembed.b_U"],
            "attn": [
                "attn.W_Q",
                "attn.W_K",
                "attn.W_V",
                "attn.W_O",
                "attn.b_Q",
                "attn.b_K",
                "attn.b_V",
                "attn.b_O",
            ],
            "mlp": ["mlp.W_in", "mlp.W_out", "mlp.W_gate", "mlp.b_in", "mlp.b_out"],
            "head_params": {
                "attn.W_Q": {"slice_dim": 0},
                "attn.W_K": {"slice_dim": 0},
                "attn.W_V": {"slice_dim": 0},
                "attn.W_O": {"slice_dim": 0},
                "attn.b_Q": {"slice_dim": 0},
                "attn.b_K": {"slice_dim": 0},
                "attn.b_V": {"slice_dim": 0},
            },
        },
        {  # GQA (TL stores KV as _W_K/_W_V with n_kv heads)
            "layer_prefixes": ["blocks"],
            "embed": ["embed.W_E"],
            "unembed": ["unembed.W_U", "unembed.b_U"],
            "attn": [
                "attn.W_Q",
                "attn._W_K",
                "attn._W_V",
                "attn.W_O",
                "attn.b_Q",
                "attn._b_K",
                "attn._b_V",
                "attn.b_O",
            ],
            "mlp": ["mlp.W_in", "mlp.W_out", "mlp.W_gate", "mlp.b_in", "mlp.b_out"],
            "head_params": {
                "attn.W_Q": {"slice_dim": 0},
                "attn._W_K": {"slice_dim": 0},
                "attn._W_V": {"slice_dim": 0},
                "attn.W_O": {"slice_dim": 0},
                "attn.b_Q": {"slice_dim": 0},
                "attn._b_K": {"slice_dim": 0},
                "attn._b_V": {"slice_dim": 0},
            },
        },
    ],
    "afmoe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.gate_proj.weight",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.gate_proj.weight": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "apertus": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.act_fn.alpha_n",
            "mlp.act_fn.alpha_p",
            "mlp.down_proj.weight",
            "mlp.up_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "arcee": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "aria_text": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.experts.fc1.weight",
            "mlp.experts.fc2.weight",
            "mlp.router.weight",
            "mlp.shared_experts.down_proj.weight",
            "mlp.shared_experts.gate_proj.weight",
            "mlp.shared_experts.up_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "bart": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "bert": {
        "layer_prefixes": ["bert.encoder.layer"],
        "embed": ["bert.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "bert-generation": {
        "layer_prefixes": ["bert.encoder.layer"],
        "embed": ["bert.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "big_bird": {
        "layer_prefixes": ["bert.encoder.layer"],
        "embed": ["bert.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "bigbird_pegasus": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "biogpt": {
        "layer_prefixes": ["biogpt.layers"],
        "embed": ["biogpt.embed_tokens.weight"],
        "unembed": ["output_projection.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "blenderbot": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "blenderbot-small": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "bloom": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.word_embeddings.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attention.dense.bias",
            "self_attention.dense.weight",
            "self_attention.query_key_value.bias",
            "self_attention.query_key_value.weight",
        ],
        "mlp": [
            "mlp.dense_4h_to_h.bias",
            "mlp.dense_4h_to_h.weight",
            "mlp.dense_h_to_4h.bias",
            "mlp.dense_h_to_4h.weight",
        ],
        "head_params": {
            "self_attention.dense.weight": {"slice_dim": 1},
            "self_attention.query_key_value.bias": {
                "fused": "interleaved",
                "slice_dim": 0,
            },
            "self_attention.query_key_value.weight": {
                "fused": "interleaved",
                "slice_dim": 0,
            },
        },
    },
    "camembert": {
        "layer_prefixes": ["roberta.encoder.layer"],
        "embed": ["roberta.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "code_llama": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "codegen": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight", "lm_head.bias"],
        "attn": ["attn.out_proj.weight", "attn.qkv_proj.weight"],
        "mlp": [
            "mlp.fc_in.bias",
            "mlp.fc_in.weight",
            "mlp.fc_out.bias",
            "mlp.fc_out.weight",
        ],
        "head_params": {
            "attn.out_proj.weight": {"slice_dim": 1},
            "attn.qkv_proj.weight": {"fused": "interleaved", "slice_dim": 0},
        },
    },
    "cpmant": {
        "layer_prefixes": ["cpmant.encoder.layers"],
        "embed": ["cpmant.input_embedding.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_att.self_attention.attention_out.weight",
            "self_att.self_attention.project_k.weight",
            "self_att.self_attention.project_q.weight",
            "self_att.self_attention.project_v.weight",
        ],
        "mlp": [
            "ffn.ffn.w_in.w_0.weight",
            "ffn.ffn.w_in.w_1.weight",
            "ffn.ffn.w_out.weight",
        ],
        "head_params": {
            "self_att.self_attention.attention_out.weight": {"slice_dim": 1},
            "self_att.self_attention.project_k.weight": {"slice_dim": 0},
            "self_att.self_attention.project_q.weight": {"slice_dim": 0},
            "self_att.self_attention.project_v.weight": {"slice_dim": 0},
        },
    },
    "ctrl": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.w.weight"],
        "unembed": ["lm_head.weight", "lm_head.bias"],
        "attn": [
            "multi_head_attention.Wk.bias",
            "multi_head_attention.Wk.weight",
            "multi_head_attention.Wq.bias",
            "multi_head_attention.Wq.weight",
            "multi_head_attention.Wv.bias",
            "multi_head_attention.Wv.weight",
            "multi_head_attention.dense.bias",
            "multi_head_attention.dense.weight",
        ],
        "mlp": ["ffn.0.bias", "ffn.0.weight", "ffn.2.bias", "ffn.2.weight"],
        "head_params": {
            "multi_head_attention.Wk.weight": {"slice_dim": 0},
            "multi_head_attention.Wq.bias": {"slice_dim": 0},
            "multi_head_attention.Wq.weight": {"slice_dim": 0},
            "multi_head_attention.Wv.bias": {"slice_dim": 0},
            "multi_head_attention.Wv.weight": {"slice_dim": 0},
            "multi_head_attention.dense.weight": {"slice_dim": 1},
        },
    },
    "cwm": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "data2vec-text": {
        "layer_prefixes": ["data2vec_text.encoder.layer"],
        "embed": ["data2vec_text.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "electra": {
        "layer_prefixes": ["electra.encoder.layer"],
        "embed": ["electra.embeddings.word_embeddings.weight"],
        "unembed": ["generator_lm_head.weight", "generator_lm_head.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "ernie": {
        "layer_prefixes": ["ernie.encoder.layer"],
        "embed": ["ernie.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "ernie4_5": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "ernie4_5_moe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "exaone4": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "exaone_moe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "falcon": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.word_embeddings.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attention.dense.weight",
            "self_attention.query_key_value.weight",
        ],
        "mlp": ["mlp.dense_4h_to_h.weight", "mlp.dense_h_to_4h.weight"],
        "head_params": {
            "self_attention.dense.weight": {"slice_dim": 1},
            "self_attention.query_key_value.weight": {
                "fused": "concat",
                "slice_dim": 0,
            },
        },
    },
    "gemma": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "gemma2": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "gemma3_text": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "gemma4_text": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "glm": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "glm4": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "glm4_moe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "gpt-sw3": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "attn.c_attn.bias",
            "attn.c_attn.weight",
            "attn.c_proj.bias",
            "attn.c_proj.weight",
        ],
        "mlp": [
            "mlp.c_fc.bias",
            "mlp.c_fc.weight",
            "mlp.c_proj.bias",
            "mlp.c_proj.weight",
        ],
        "head_params": {
            "attn.c_attn.bias": {"fused": "concat", "slice_dim": 0},
            "attn.c_attn.weight": {"fused": "concat", "slice_dim": 1},
            "attn.c_proj.weight": {"slice_dim": 0},
        },
    },
    "gpt2": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "attn.c_attn.bias",
            "attn.c_attn.weight",
            "attn.c_proj.bias",
            "attn.c_proj.weight",
        ],
        "mlp": [
            "mlp.c_fc.bias",
            "mlp.c_fc.weight",
            "mlp.c_proj.bias",
            "mlp.c_proj.weight",
        ],
        "head_params": {
            "attn.c_attn.bias": {"fused": "concat", "slice_dim": 0},
            "attn.c_attn.weight": {"fused": "concat", "slice_dim": 1},
            "attn.c_proj.weight": {"slice_dim": 0},
        },
    },
    "gpt_bigcode": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "attn.c_attn.bias",
            "attn.c_attn.weight",
            "attn.c_proj.bias",
            "attn.c_proj.weight",
        ],
        "mlp": [
            "mlp.c_fc.bias",
            "mlp.c_fc.weight",
            "mlp.c_proj.bias",
            "mlp.c_proj.weight",
        ],
        "head_params": {
            "attn.c_attn.bias": {"fused": "concat", "slice_dim": 0},
            "attn.c_attn.weight": {"fused": "concat", "slice_dim": 0},
            "attn.c_proj.weight": {"slice_dim": 1},
        },
    },
    "gpt_neo": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "attn.attention.k_proj.weight",
            "attn.attention.out_proj.bias",
            "attn.attention.out_proj.weight",
            "attn.attention.q_proj.weight",
            "attn.attention.v_proj.weight",
        ],
        "mlp": [
            "mlp.c_fc.bias",
            "mlp.c_fc.weight",
            "mlp.c_proj.bias",
            "mlp.c_proj.weight",
        ],
        "head_params": {
            "attn.attention.k_proj.weight": {"slice_dim": 0},
            "attn.attention.out_proj.weight": {"slice_dim": 1},
            "attn.attention.q_proj.weight": {"slice_dim": 0},
            "attn.attention.v_proj.weight": {"slice_dim": 0},
        },
    },
    "gpt_neox": {
        "layer_prefixes": ["gpt_neox.layers"],
        "embed": ["gpt_neox.embed_in.weight"],
        "unembed": ["embed_out.weight"],
        "attn": [
            "attention.dense.bias",
            "attention.dense.weight",
            "attention.query_key_value.bias",
            "attention.query_key_value.weight",
        ],
        "mlp": [
            "mlp.dense_4h_to_h.bias",
            "mlp.dense_4h_to_h.weight",
            "mlp.dense_h_to_4h.bias",
            "mlp.dense_h_to_4h.weight",
        ],
        "head_params": {
            "attention.dense.weight": {"slice_dim": 1},
            "attention.query_key_value.bias": {"fused": "interleaved", "slice_dim": 0},
            "attention.query_key_value.weight": {
                "fused": "interleaved",
                "slice_dim": 0,
            },
        },
    },
    "gpt_neox_japanese": {
        "layer_prefixes": ["gpt_neox_japanese.layers"],
        "embed": ["gpt_neox_japanese.embed_in.weight"],
        "unembed": ["embed_out.weight"],
        "attn": [
            "attention.dense.weight",
            "attention.dense_bias",
            "attention.query_key_value.weight",
        ],
        "mlp": ["mlp.dense_4h_to_h.weight", "mlp.dense_h_to_4h.weight"],
        "head_params": {
            "attention.dense.weight": {"slice_dim": 1},
            "attention.query_key_value.weight": {
                "fused": "interleaved",
                "slice_dim": 0,
            },
        },
    },
    "gpt_oss": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.bias",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.sinks",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.experts.down_proj",
            "mlp.experts.down_proj_bias",
            "mlp.experts.gate_up_proj",
            "mlp.experts.gate_up_proj_bias",
            "mlp.router.bias",
            "mlp.router.weight",
        ],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.sinks": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "gptj": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight", "lm_head.bias"],
        "attn": [
            "attn.k_proj.weight",
            "attn.out_proj.weight",
            "attn.q_proj.weight",
            "attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.fc_in.bias",
            "mlp.fc_in.weight",
            "mlp.fc_out.bias",
            "mlp.fc_out.weight",
        ],
        "head_params": {
            "attn.k_proj.weight": {"slice_dim": 0},
            "attn.out_proj.weight": {"slice_dim": 1},
            "attn.q_proj.weight": {"slice_dim": 0},
            "attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "granite": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "granitemoe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "block_sparse_moe.input_linear.weight",
            "block_sparse_moe.output_linear.weight",
            "block_sparse_moe.router.layer.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "granitemoeshared": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "block_sparse_moe.input_linear.weight",
            "block_sparse_moe.output_linear.weight",
            "block_sparse_moe.router.layer.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "helium": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "hunyuan_v1_dense": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "hunyuan_v1_moe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.experts.down_proj",
            "mlp.experts.gate_up_proj",
            "mlp.gate.wg.weight",
            "mlp.shared_mlp.down_proj.weight",
            "mlp.shared_mlp.gate_proj.weight",
            "mlp.shared_mlp.up_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "jais2": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.bias",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.down_proj.bias",
            "mlp.down_proj.weight",
            "mlp.up_proj.bias",
            "mlp.up_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "lfm2": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "feed_forward.w1.weight",
            "feed_forward.w2.weight",
            "feed_forward.w3.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "llama": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "llama4_text": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "feed_forward.experts.down_proj",
            "feed_forward.experts.gate_up_proj",
            "feed_forward.router.weight",
            "feed_forward.shared_expert.down_proj.weight",
            "feed_forward.shared_expert.gate_proj.weight",
            "feed_forward.shared_expert.up_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "mbart": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "megatron-bert": {
        "layer_prefixes": ["bert.encoder.layer"],
        "embed": ["bert.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "minimax": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.experts.down_proj", "mlp.experts.gate_up_proj", "mlp.gate.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "ministral": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "ministral3": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "mistral": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "mixtral": [
        {  # transformers >= 5.5 (fused expert weights)
            "layer_prefixes": ["model.layers"],
            "embed": ["model.embed_tokens.weight"],
            "unembed": ["lm_head.weight"],
            "attn": [
                "self_attn.k_proj.weight",
                "self_attn.o_proj.weight",
                "self_attn.q_proj.weight",
                "self_attn.v_proj.weight",
            ],
            "mlp": [
                "mlp.experts.down_proj",
                "mlp.experts.gate_up_proj",
                "mlp.gate.weight",
            ],
            "head_params": {
                "self_attn.k_proj.weight": {"slice_dim": 0},
                "self_attn.o_proj.weight": {"slice_dim": 1},
                "self_attn.q_proj.weight": {"slice_dim": 0},
                "self_attn.v_proj.weight": {"slice_dim": 0},
            },
        },
        {  # transformers < 5.5 (per-expert indexed weights, block_sparse_moe prefix)
            "layer_prefixes": ["model.layers"],
            "embed": ["model.embed_tokens.weight"],
            "unembed": ["lm_head.weight"],
            "attn": [
                "self_attn.k_proj.weight",
                "self_attn.o_proj.weight",
                "self_attn.q_proj.weight",
                "self_attn.v_proj.weight",
            ],
            "mlp": [
                "block_sparse_moe.gate.weight",
                "block_sparse_moe.experts.0.w1.weight",
                "block_sparse_moe.experts.0.w2.weight",
                "block_sparse_moe.experts.0.w3.weight",
            ],
            "head_params": {
                "self_attn.k_proj.weight": {"slice_dim": 0},
                "self_attn.o_proj.weight": {"slice_dim": 1},
                "self_attn.q_proj.weight": {"slice_dim": 0},
                "self_attn.v_proj.weight": {"slice_dim": 0},
            },
        },
    ],
    "mpt": {
        "layer_prefixes": ["transformer.blocks"],
        "embed": ["transformer.wte.weight"],
        "unembed": ["lm_head.weight"],
        "attn": ["attn.Wqkv.weight", "attn.out_proj.weight"],
        "mlp": ["ffn.down_proj.weight", "ffn.up_proj.weight"],
        "head_params": {
            "attn.Wqkv.weight": {"fused": "concat", "slice_dim": 0},
            "attn.out_proj.weight": {"slice_dim": 1},
        },
    },
    "mvp": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "nanochat": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.fc1.weight", "mlp.fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "nemotron": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "olmo": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "openai-gpt": {
        "layer_prefixes": ["transformer.h"],
        "embed": ["transformer.tokens_embed.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "attn.c_attn.bias",
            "attn.c_attn.weight",
            "attn.c_proj.bias",
            "attn.c_proj.weight",
        ],
        "mlp": [
            "mlp.c_fc.bias",
            "mlp.c_fc.weight",
            "mlp.c_proj.bias",
            "mlp.c_proj.weight",
        ],
        "head_params": {
            "attn.c_attn.bias": {"fused": "concat", "slice_dim": 0},
            "attn.c_attn.weight": {"fused": "concat", "slice_dim": 1},
            "attn.c_proj.weight": {"slice_dim": 0},
        },
    },
    "opt": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "pegasus": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "persimmon": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.dense.bias",
            "self_attn.dense.weight",
            "self_attn.query_key_value.bias",
            "self_attn.query_key_value.weight",
        ],
        "mlp": [
            "mlp.dense_4h_to_h.bias",
            "mlp.dense_4h_to_h.weight",
            "mlp.dense_h_to_4h.bias",
            "mlp.dense_h_to_4h.weight",
        ],
        "head_params": {
            "self_attn.dense.weight": {"slice_dim": 1},
            "self_attn.query_key_value.bias": {"fused": "interleaved", "slice_dim": 0},
            "self_attn.query_key_value.weight": {
                "fused": "interleaved",
                "slice_dim": 0,
            },
        },
    },
    "phi": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight", "lm_head.bias"],
        "attn": [
            "self_attn.dense.bias",
            "self_attn.dense.weight",
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.fc1.bias", "mlp.fc1.weight", "mlp.fc2.bias", "mlp.fc2.weight"],
        "head_params": {
            "self_attn.dense.weight": {"slice_dim": 1},
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "phi3": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": ["self_attn.o_proj.weight", "self_attn.qkv_proj.weight"],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_up_proj.weight"],
        "head_params": {
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.qkv_proj.weight": {"fused": "concat", "slice_dim": 0},
        },
    },
    "phimoe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.experts.down_proj",
            "mlp.experts.gate_up_proj",
            "mlp.router.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "plbart": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "qwen2": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "qwen2_moe": [
        {  # transformers >= 5.5 (fused expert weights)
            "layer_prefixes": ["model.layers"],
            "embed": ["model.embed_tokens.weight"],
            "unembed": ["lm_head.weight"],
            "attn": [
                "self_attn.k_proj.bias",
                "self_attn.k_proj.weight",
                "self_attn.o_proj.weight",
                "self_attn.q_proj.bias",
                "self_attn.q_proj.weight",
                "self_attn.v_proj.bias",
                "self_attn.v_proj.weight",
            ],
            "mlp": [
                "mlp.experts.down_proj",
                "mlp.experts.gate_up_proj",
                "mlp.gate.weight",
                "mlp.shared_expert.down_proj.weight",
                "mlp.shared_expert.gate_proj.weight",
                "mlp.shared_expert.up_proj.weight",
                "mlp.shared_expert_gate.weight",
            ],
            "head_params": {
                "self_attn.k_proj.bias": {"slice_dim": 0},
                "self_attn.k_proj.weight": {"slice_dim": 0},
                "self_attn.o_proj.weight": {"slice_dim": 1},
                "self_attn.q_proj.bias": {"slice_dim": 0},
                "self_attn.q_proj.weight": {"slice_dim": 0},
                "self_attn.v_proj.bias": {"slice_dim": 0},
                "self_attn.v_proj.weight": {"slice_dim": 0},
            },
        },
        {  # transformers < 5.5 (per-expert indexed weights)
            "layer_prefixes": ["model.layers"],
            "embed": ["model.embed_tokens.weight"],
            "unembed": ["lm_head.weight"],
            "attn": [
                "self_attn.k_proj.bias",
                "self_attn.k_proj.weight",
                "self_attn.o_proj.weight",
                "self_attn.q_proj.bias",
                "self_attn.q_proj.weight",
                "self_attn.v_proj.bias",
                "self_attn.v_proj.weight",
            ],
            "mlp": [
                "mlp.gate.weight",
                "mlp.experts.0.gate_proj.weight",
                "mlp.experts.0.up_proj.weight",
                "mlp.experts.0.down_proj.weight",
                "mlp.shared_expert.gate_proj.weight",
                "mlp.shared_expert.up_proj.weight",
                "mlp.shared_expert.down_proj.weight",
                "mlp.shared_expert_gate.weight",
            ],
            "head_params": {
                "self_attn.k_proj.bias": {"slice_dim": 0},
                "self_attn.k_proj.weight": {"slice_dim": 0},
                "self_attn.o_proj.weight": {"slice_dim": 1},
                "self_attn.q_proj.bias": {"slice_dim": 0},
                "self_attn.q_proj.weight": {"slice_dim": 0},
                "self_attn.v_proj.bias": {"slice_dim": 0},
                "self_attn.v_proj.weight": {"slice_dim": 0},
            },
        },
    ],
    "qwen3": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "qwen3_moe": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.experts.down_proj", "mlp.experts.gate_up_proj", "mlp.gate.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "rembert": {
        "layer_prefixes": ["rembert.encoder.layer"],
        "embed": ["rembert.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "roberta": {
        "layer_prefixes": ["roberta.encoder.layer"],
        "embed": ["roberta.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "roberta-prelayernorm": {
        "layer_prefixes": ["roberta_prelayernorm.encoder.layer"],
        "embed": ["roberta_prelayernorm.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "roc_bert": {
        "layer_prefixes": ["roc_bert.encoder.layer"],
        "embed": ["roc_bert.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "roformer": {
        "layer_prefixes": ["roformer.encoder.layer"],
        "embed": ["roformer.embeddings.word_embeddings.weight"],
        "unembed": ["cls.predictions.decoder.weight", "cls.predictions.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "seed_oss": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "smollm3": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "solar_open": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.experts.down_proj",
            "mlp.experts.gate_up_proj",
            "mlp.gate.weight",
            "mlp.shared_experts.down_proj.weight",
            "mlp.shared_experts.gate_proj.weight",
            "mlp.shared_experts.up_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "stablelm": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "starcoder2": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.o_proj.bias",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": [
            "mlp.c_fc.bias",
            "mlp.c_fc.weight",
            "mlp.c_proj.bias",
            "mlp.c_proj.weight",
        ],
        "head_params": {
            "self_attn.k_proj.bias": {"slice_dim": 0},
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "trocr": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["output_projection.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "vaultgemma": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.o_proj.weight",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["mlp.down_proj.weight", "mlp.gate_proj.weight", "mlp.up_proj.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.o_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "whisper": {
        "layer_prefixes": ["model.decoder.layers"],
        "embed": ["model.decoder.embed_tokens.weight"],
        "unembed": ["proj_out.weight"],
        "attn": [
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "xglm": {
        "layer_prefixes": ["model.layers"],
        "embed": ["model.embed_tokens.weight"],
        "unembed": ["lm_head.weight"],
        "attn": [
            "self_attn.k_proj.bias",
            "self_attn.k_proj.weight",
            "self_attn.out_proj.bias",
            "self_attn.out_proj.weight",
            "self_attn.q_proj.bias",
            "self_attn.q_proj.weight",
            "self_attn.v_proj.bias",
            "self_attn.v_proj.weight",
        ],
        "mlp": ["fc1.bias", "fc1.weight", "fc2.bias", "fc2.weight"],
        "head_params": {
            "self_attn.k_proj.weight": {"slice_dim": 0},
            "self_attn.out_proj.weight": {"slice_dim": 1},
            "self_attn.q_proj.bias": {"slice_dim": 0},
            "self_attn.q_proj.weight": {"slice_dim": 0},
            "self_attn.v_proj.bias": {"slice_dim": 0},
            "self_attn.v_proj.weight": {"slice_dim": 0},
        },
    },
    "xlm": {
        "layer_prefixes": [
            "transformer.attentions",
            "transformer.ffns",
            "transformer.layer_norm1",
            "transformer.layer_norm2",
        ],
        "embed": ["transformer.embeddings.weight"],
        "unembed": ["pred_layer.proj.weight", "pred_layer.proj.bias"],
        "attn": [
            "k_lin.bias",
            "k_lin.weight",
            "out_lin.bias",
            "out_lin.weight",
            "q_lin.bias",
            "q_lin.weight",
            "v_lin.bias",
            "v_lin.weight",
        ],
        "mlp": ["lin1.bias", "lin1.weight", "lin2.bias", "lin2.weight"],
        "head_params": {
            "k_lin.weight": {"slice_dim": 0},
            "out_lin.weight": {"slice_dim": 1},
            "q_lin.bias": {"slice_dim": 0},
            "q_lin.weight": {"slice_dim": 0},
            "v_lin.bias": {"slice_dim": 0},
            "v_lin.weight": {"slice_dim": 0},
        },
    },
    "xlm-roberta": {
        "layer_prefixes": ["roberta.encoder.layer"],
        "embed": ["roberta.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "xlm-roberta-xl": {
        "layer_prefixes": ["roberta.encoder.layer"],
        "embed": ["roberta.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
    "xmod": {
        "layer_prefixes": ["roberta.encoder.layer"],
        "embed": ["roberta.embeddings.word_embeddings.weight"],
        "unembed": ["lm_head.decoder.weight", "lm_head.decoder.bias"],
        "attn": [
            "attention.output.dense.bias",
            "attention.output.dense.weight",
            "attention.self.key.bias",
            "attention.self.key.weight",
            "attention.self.query.bias",
            "attention.self.query.weight",
            "attention.self.value.bias",
            "attention.self.value.weight",
        ],
        "mlp": [
            "intermediate.dense.bias",
            "intermediate.dense.weight",
            "output.adapter_modules.en_XX.dense1.bias",
            "output.adapter_modules.en_XX.dense1.weight",
            "output.adapter_modules.en_XX.dense2.bias",
            "output.adapter_modules.en_XX.dense2.weight",
            "output.dense.bias",
            "output.dense.weight",
        ],
        "head_params": {
            "attention.output.dense.weight": {"slice_dim": 1},
            "attention.self.key.weight": {"slice_dim": 0},
            "attention.self.query.bias": {"slice_dim": 0},
            "attention.self.query.weight": {"slice_dim": 0},
            "attention.self.value.bias": {"slice_dim": 0},
            "attention.self.value.weight": {"slice_dim": 0},
        },
    },
}
